name: test
on: [push, pull_request]
jobs:
  lint:
    name: lint
    steps:
    - name: checkout
      uses: actions/checkout@v2.1.0
    - name: set up python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.6
    - name: install vim-vint
      run: |
        python -m pip install --upgrade pip
        pip install vim-vint pathlib
    - name: lint
      run: ./scripts/lint vim-8.2
  test:
    name: Test
    runs-on: ubuntu-latest
		matrix:
			go: ['1.14', '1.13']
			vim: ['vim-8.0', 'vim-8.2', 'nvim']
    steps:
    - name: setup Go
      uses: actions/setup-go@v2.0.3
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: set up python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.6
    - name: install covimerage
      run: |
        python -m pip install --upgrade pip
        pip install covimerage==0.2.1 codecov pathlib
    - name: checkout
      uses: actions/checkout@v2.1.0
		- name: install vim
			with:
				vim_version: ${{ matrix.vim }}
			run: ./scripts/install-vim $INPUT_VIM_VERSION
		- name: test
			with:
				vim_version: ${{ matrix.vim }}
      run: ./scripts/test -c $INPUT_VIM_VERSION
